CREATE TABLE `serviceRequest`
(
    `id`                        bigint(18) unsigned NOT NULL AUTO_INCREMENT,
    `srType`                    varchar(50)  DEFAULT NULL,
    `unitNumber`                varchar(255) DEFAULT NULL,
    `complexname`               varchar(255) DEFAULT NULL,
    `StreetNumber`              varchar(45)  DEFAULT NULL,
    `streetName`                varchar(255) DEFAULT NULL,
    `cityId`                    int(7) DEFAULT '0',
    `processedStatus`           tinyint(1) DEFAULT '0',
    `listingId`                 bigint(18) DEFAULT NULL,
    `agentId`                   bigint(18) DEFAULT '0',
    `bokerageId`                bigint(18) DEFAULT NULL,

    `firstName`                 VARCHAR(45) NULL,
    `lastName`                  VARCHAR(45) NULL,
    `email`                     VARCHAR(45) NOT NULL,
    `phoneNumber`               VARCHAR(20) NULL,
    `address1`                  VARCHAR(255) NULL,
    `address2`                  VARCHAR(255) NULL,
    `cityName`                  varchar(45)  DEFAULT NULL,
    `stateName`                 varchar(45)  DEFAULT NULL,
    `zip`                       varchar(5)   DEFAULT NULL,
    `isTransactionManaged`      tinyint(1) DEFAULT '0',
    `clientPhoneNumber`         VARCHAR(20) NULL,
    `mlsId`                     varchar(20) NULL,
    `userType`                  varchar(45) NULL,
    `propertyPrice`             double NULL,
    `propertyArea`              double NULL,
    `bedroomCount`              INT NULL,
    `bathroomCount`             INT NULL,
    `builtYear`                 INT NULL,
    `propertySize`              INT NULL,
    `otherInfo`                 VARCHAR(255) NULL,
    `commissionPercentage`      DOUBLE NULL,
    `companyContactFirstname`   VARCHAR(45) NULL,
    `companyContactLastname`    VARCHAR(45) NULL,
    `companyContactEmail`       VARCHAR(45) NULL,
    `companyContactPhoneNumber` VARCHAR(20) NULL,
    `isReferred`                tinyint(1) DEFAULT '0',
    `referralAgentName`         VARCHAR(45) NULL,
    `referralFirm`              VARCHAR(45) NULL,
    `referralFee`               DECIMAL(10, 2) NULL,
    `isLeadReferral`            tinyint(1) DEFAULT '0',
    `leadReferralName`          VARCHAR(45) NULL,
    `created`                   datetime     DEFAULT NULL,
    `created_by`                bigint(18) DEFAULT '1',
    `updated`                   datetime     DEFAULT NULL,
    `updated_by`                bigint(18) DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;